config/routes.rb
Mikrokamnew::Application.routes.draw do  

  resources :infos

  devise_for :admins

  resources :admins
  resources :tabs
  resources :advices
  resources :sliders
  resources :menus
  resources :contents
  resources :tests
  resources :stylesheets

  scope "/admin" do
    resources :menus, :contents, :sliders, :tabs
  end  

  resources :home do
    member do
      get 'content'
      get 'advice'
      get 'slider'
      get 'active_tab_ajax'
      get 'all_active'
      get 'service'
    end
  end 

  get "home/index"
  
  match 'admin' => 'admins#index'
  match 'admins' => 'admins#index'

  match "infos/:id/show_tabs" => "infos#show_tabs", :as => "show_the_tabs"
  

  root :to => "home#index"

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  #Devise
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
end

app/models/advice.rb
class Advice < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  has_one :menu
  has_one :info
  has_many :tabs, :through => :info

  # Ha azt szeretnenk hogy az url-ben szerpepljen a a tartlomnal megadott url erteke akkor ezt kell engedelyezni

  #def to_param
  #  url
  #end



end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :content
  has_many :tabs
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :content
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/styles.rb
class Styles < ActiveRecord::Base
end

app/models/stylesheet.rb
class Stylesheet < ActiveRecord::Base
end

app/models/tab.rb
class Tab < ActiveRecord::Base
  belongs_to :info
  has_one :content, :through => :info
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController

  before_filter :authenticate_admin!
  layout 'admin'  
  
  def index
    @sliders = Slider.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sliders }
    end
  end

  # GET /sliders/1
  # GET /sliders/1.xml
  def show
    @slider = Slider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @slider }
    end
  end

  # GET /sliders/new
  # GET /sliders/new.xml
  def new
    @slider = Slider.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @slider }
    end
  end

  # GET /sliders/1/edit
  def edit
    @slider = Slider.find(params[:id])
  end

  # POST /sliders
  # POST /sliders.xml
  def create
    @slider = Slider.new(params[:slider])

    respond_to do |format|
      if @slider.save
        format.html { redirect_to(@slider, :notice => 'Slider was successfully created.') }
        format.xml  { render :xml => @slider, :status => :created, :location => @slider }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @slider.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sliders/1
  # PUT /sliders/1.xml
  def update
    @slider = Slider.find(params[:id])    
      if @slider.update_attributes(params[:slider])
        redirect_to sliders_path, :notice => 'Slider was successfully updated.'
      else
        render :action => "edit"    
      end    
  end

  # DELETE /sliders/1
  # DELETE /sliders/1.xml
  def destroy
    @slider = Slider.find(params[:id])
    @slider.destroy

    respond_to do |format|
      format.html { redirect_to(sliders_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/stylesheet_helper.rb
module StylesheetHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/sliders/_form.html.erb
<%= form_for(@slider) do |f| %>
  <% if @slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slider.errors.count, "error") %> prohibited this slider from being saved:</h2>

      <ul>
      <% @slider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Cím" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :short_description, "Rövid leírás" %><br />
    <%= f.text_field :short_description %>
  </div>

  <div class="field">
    <%= f.label :description, "Leírás" %><br />
    <%= f.cktext_area :description, :toolbar=>'slim', :width=>'100%', :height=>'200px', :skin => "v2" %>
  </div>

  <div class="field">
    <%= f.label :image_tag, "Kép hozzárendelés" %><br />
    <%= f.select(:image_tag, options_for_select([['Kép-1', 1], ['Kép-2', 2], ['Kép-3', 3]])) %>
  </div>

  <%= link_to "Kép-1", "#" %><%= image_tag("kep_1.png", :class=> "form_image") %><br/>
  <%= link_to "Kép-2", "#" %><%= image_tag("kep_2.png", :class=> "form_image")%><br/>
  <%= link_to "Kép-3", "#" %><%= image_tag("kep_3.png", :class=> "form_image")%><br/>

  <br/><br/>

  <div class="actions">
    <%= f.submit "Rendben!" %>
  </div>
<% end %>

app/views/sliders/edit.html.erb
<h1>Szerkesztés : <%= @slider.title %></h1>

<%= render 'form' %>

<%= link_to 'Vissza', sliders_path %>

app/views/sliders/index.html.erb
<h1>Slider-ek listája</h1>

<div class="add_new">
  <%= link_to 'Új slider felvitele', new_slider_path %>
  <%= link_to 'Vissza', admins_path %>
</div>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Cím</th>
      <th scope="col">&nbsp;</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @sliders.each do |slider| %>
      <tr>
        <td><%= slider.title %></td>
        <td><%= link_to 'Módosít', edit_slider_path(slider) %></td>
        <td class="delete"><%= link_to 'Töröl', slider, :confirm => 'Biztosan törlöd?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/sliders/new.html.erb
<h1>Új slide felvitele</h1>

<%= render 'form' %>

<%= link_to 'Vissza', sliders_path %>

app/views/sliders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @slider.title %>
</p>

<p>
  <b>Description:</b>
  <%= @slider.description %>
</p>


<%= link_to 'Edit', edit_slider_path(@slider) %> |
<%= link_to 'Back', sliders_path %>

<%= debug params %>

app/views/sliders/show_all_slide.html.erb
Show all slide








 