config/routes.rb
Mikrokamnew::Application.routes.draw do  

  resources :infos

  devise_for :admins

  resources :admins
  resources :tabs
  resources :advices
  resources :sliders
  resources :menus
  resources :contents
  resources :tests
  resources :stylesheets

  scope "/admin" do
    resources :menus, :contents, :sliders, :tabs
  end  

  resources :home do
    member do
      get 'content'
      get 'advice'
      get 'slider'
      get 'active_tab_ajax'
      get 'all_active'
      get 'service'
    end
  end 

  get "home/index"
  
  match 'admin' => 'admins#index'
  match 'admins' => 'admins#index'

  match "infos/:id/show_tabs" => "infos#show_tabs", :as => "show_the_tabs"
  

  root :to => "home#index"

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  #Devise
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
end

app/models/advice.rb
class Advice < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  has_one :menu
  has_one :info
  has_many :tabs, :through => :info

  # Ha azt szeretnenk hogy az url-ben szerpepljen a a tartlomnal megadott url erteke akkor ezt kell engedelyezni

  #def to_param
  #  url
  #end



end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :content
  has_many :tabs
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :content
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/styles.rb
class Styles < ActiveRecord::Base
end

app/models/stylesheet.rb
class Stylesheet < ActiveRecord::Base
end

app/models/tab.rb
class Tab < ActiveRecord::Base
  belongs_to :info
  has_one :content, :through => :info
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/contents_controller.rb
# encoding: UTF-8
class ContentsController < ApplicationController

  before_filter :authenticate_admin!
  layout 'admin'
  
  # GET /contents
  # GET /contents.xml
  def index
    @info = Info.new
    @info_contents = Info.all
    @contents = Content.find(:all, :order => "sort_number ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.xml
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.xml
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.xml
  def create
    @content = Content.new(params[:content])
    
      if @content.save
        redirect_to contents_path, :notice => 'Content was successfully created.'
      else
        render :action => "new"        
      end    
  end

  # PUT /contents/1
  # PUT /contents/1.xml
  def update
    @content = Content.find(params[:id])
    
      if @content.update_attributes(params[:content])
        redirect_to contents_path, :notice => 'Content was successfully updated.'
      else
        render :action => "edit"      
      end
    
  end

  # DELETE /contents/1
  # DELETE /contents/1.xml
  def destroy
    @content = Content.find(params[:id])
    if (params[:id] == '1')
      redirect_to contents_path, :notice => 'Ezt a tartalmat nem törölheted, de módosíthatod (id=1)'
    else
       #render :text => "#{params[:id]}"
      @content.destroy
      redirect_to contents_path, :notice => 'Sikeres törlés!'
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/stylesheet_helper.rb
module StylesheetHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Cím" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :sort_number, "Sorrend" %><br />
    <%= f.text_field :sort_number %>
  </div>

  <div class="field">
    <%= f.label :content, "Tartalom" %><br />
    <div class="ckeditor">
      <%= f.cktext_area :content, :toolbar=>'light', :width=>'100%', :height=>'200px', :skin => "office2003" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Rendben!" %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Szerkesztés : <%= @content.title %></h1>

<%= render 'form' %>

<%= link_to 'Vissza', contents_path %>

app/views/contents/index.html.erb
<h1>Tartalmak listája</h1>

<div class="add_new">
  <%= link_to 'Új tartalom felvitele', new_content_path %>
  <%= link_to 'Vissza', admins_path %>
</div>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Cím</th>
      <th scope="col">Sorrend</th>
      <th scope="col">&nbsp;</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
  <% @contents.each do |content| %>

      <tr>

        <td><%= content.title %></td>
        <td><%= content.sort_number %></td>

        <td><%= link_to 'Módosít', edit_content_path(content) %></td>
        <td class="delete"><%= link_to 'Töröl', content, :confirm => 'Biztosan törlöd?', :method => :delete %></td>

      </tr>

  <% end %>
  </tbody>

</table>

app/views/contents/new.html.erb
<h1>Új tartalom felvitele</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p>
  <b>Title:</b>
  <%= @content.title %>
</p>

<p>
  <b>Content:</b>
  <%= @content.content %>
</p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>