config/routes.rb
Mikrokamnew::Application.routes.draw do  

  resources :infos

  devise_for :admins

  resources :admins
  resources :tabs
  resources :advices
  resources :sliders
  resources :menus
  resources :contents
  resources :tests
  resources :stylesheets

  scope "/admin" do
    resources :menus, :contents, :sliders, :tabs
  end  

  resources :home do
    member do
      get 'content'
      get 'advice'
      get 'slider'
      get 'active_tab_ajax'
      get 'all_active'
      get 'service'
    end
  end 

  get "home/index"
  
  match 'admin' => 'admins#index'
  match 'admins' => 'admins#index'

  match "infos/:id/show_tabs" => "infos#show_tabs", :as => "show_the_tabs"
  

  root :to => "home#index"

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  #Devise
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
end

app/models/advice.rb
class Advice < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  has_one :menu
  has_one :info
  has_many :tabs, :through => :info

  # Ha azt szeretnenk hogy az url-ben szerpepljen a a tartlomnal megadott url erteke akkor ezt kell engedelyezni

  #def to_param
  #  url
  #end



end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :content
  has_many :tabs
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :content
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/styles.rb
class Styles < ActiveRecord::Base
end

app/models/stylesheet.rb
class Stylesheet < ActiveRecord::Base
end

app/models/tab.rb
class Tab < ActiveRecord::Base
  belongs_to :info
  has_one :content, :through => :info
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/index.html.erb
<h1>Welcome Admin!</h1>

<div class="span-16">

  <div class="span-8">
    <div class="admin_main">
      <%= link_to "Menu items", menus_path %>
    </div>
  </div>
  <div class="span-8 last">
    <div class="admin_main">
      <%= link_to "Content items", contents_path%>
    </div>
  </div>

  <div class="span-8">
    <div class="admin_main">
      <%= link_to "Slider items", sliders_path%>
  </div>
  </div>
  <div class="span-8 last">
    <div class="admin_main">
      <%= link_to "Advice items", advices_path%>
    </div>
  </div>

  <div class="span-16">
    <div class="admin_main">
      <%= link_to "Tab items", tabs_path%>
    </div>
  </div>
  
</div>

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this advice from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Jelszó" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Rendben!" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Adminisztrátor szerkesztése</h1>

<%= render 'form' %>

app/views/admins/index.html.erb
<div class="span-24">
   <%= render :partial => "shared/admin_info" %>    
</div>

<!-- TEMPLATE TABLE --------------------------------------------------------------------------------------------------->

<h2>Template módosítása</h2>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Template</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= link_to"Template módosítása", stylesheets_path %></td>
      </tr>
  </tbody>

</table>

<br/><br/>

<!-- END TEMPLATE TABLE -->

<!-- ADMIN TABLE ------------------------------------------------------------------------------------------------------>

<h2>Adminisztrátorok szerkesztése</h2>

<div class="add_new">
  <%= link_to "Új adminisztrátor hozzáadása", new_admin_path %>
</div>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">&nbsp;</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to"#{admin.email}", edit_admin_path(admin) %></td>
        <td><%= link_to"Módosít", edit_admin_path(admin) %></td>
        <td class="delete"><%= link_to"Töröl", admin, :confirm => 'Are you sure?', :method => "delete" %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<!-- END ADMIN TABLE -->

<br/><br/>

<!-- TARTALOM TABLE --------------------------------------------------------------------------------------------------->

<h2>Tartalom szerkesztése</h2>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Szerkeszthető felületek :</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to "Tartalom módosítása", contents_path%></td>
    </tr>
    <tr>
      <td><%= link_to "Hírek módosítása", advices_path%></td>
    </tr>
  </tbody>

</table>

<!-- END TARTALOM TABLE -->

<br/><br/>

<!-- MENU TABLE -->

<h2>Menüpontok szerkesztése</h2>

<table id="box-table-a">

  <thead>
    <tr>
      <th scope="col">Szerkeszthető felületek :</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to "Menüpontok módosítása", menus_path %></td>
    </tr>
  </tbody>

</table>

<!-- END MENU TABLE -->

<br/><br/>

<!-- TARTALOM TABLE --------------------------------------------------------------------------------------------------->

<h2>Slider szerkesztése</h2>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Slider a fejlécben :</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to "Slider a fejlécben", sliders_path%></td>
    </tr>
  </tbody>

</table>

<!-- END TARTALOM TABLE -->

<br/><br/>

<!-- FULEKKEL ELLATOTT TERULET TABLE ---------------------------------------------------------------------------------->

<h2>Fülekkel ellátott terület szerkesztése</h2>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Szerkeszthető felületek :</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to "Fülekkel ellátott területek", infos_path%></td>
    </tr>
    <tr>
      <td><%= link_to "Fülek", tabs_path%></td>
    </tr>
  </tbody>

</table>

<!-- END TARTALOM TABLE -->

<br/><br/>

app/views/admins/new.html.erb
<h1>Új adminisztrátor létrehozása!</h1>

<%= render 'form' %>

app/views/shared/_admin_info.html.erb
<div class="admin_info">
  <% if admin_signed_in? %>
    <div class="admin_image">
      <%= image_tag("admin.png") %>
    </div>
    <div class="admin_text">
      Email : <b><%= current_admin.email %></b><br/>
      Beléptél : <%= current_admin.current_sign_in_at %><br/>
      IP : <%= current_admin.current_sign_in_ip %><br/>
      <div class="logout">
        <%= link_to "Kijelentkezés az adminisztrátori felületről!", destroy_admin_session_path %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_advice.html.erb
<div class="advice_title"><%= link_to "#{advice.title}", advice_home_path(advice) %></div>
<div class="advice_content">
  <% truncated_advice = truncate("#{advice.description}", :length => 200, :omission => "...") %>
  <%= raw truncated_advice %>
</div>
    

app/views/shared/_content.html.erb
<div class="advice_title"><%= link_to"#{content.title}", content_home_path(content) %></div>
<div class="advice_content">
  <% truncated_content = truncate("#{content.content}", :length => 200, :omission => "...") %>
  <%= raw truncated_content %>
</div>

app/views/shared/_index_page.html.erb
<% content_for :menu do %>
  <ul class="menu">
    <% @menus.each do |menu| %>
      <li class="button"><%= link_to "#{menu.title}", content_home_path(menu.content) %></li>
    <% end %>
  </ul>
<% end %>

<% if @container == "content"  %>

  <h1><%= @content.title %></h1>
  <%= raw @content.content %>

<% elsif @container == "advice" %>

  <h1><%= @advice.title %></h1>
  <%= raw @advice.description %>

<% else %>

  <h1><%= @slider.title %></h1>
  <%= raw @slider.description %>

<% end %>

<% content_for :slider do %>

  <!-- Slideshow here! -->

            <!-- "previous slide" button -->
            <a class="backward">prev</a>

            <!-- container for the slides -->
            <div class="images">

              <% @slides.each do |slide| %>
                <div>
                  <h3><%= slide.title %></h3>
                  <p>
                   <%= link_to image_tag("kep_#{slide.image_tag}.png"), slider_home_path(slide), :class => "slide_image_link" %>
                   <% truncated_description = truncate("#{slide.short_description}", :length => 250, :omission => "...") %>
                   <%= link_to "#{ raw truncated_description}", slider_home_path(slide), :class => "slide_short_description" %>
                  </p>
                </div>
              <% end %>

            </div>

            <!-- "next slide" button -->
            <a class="forward">next</a>

            <!-- the tabs -->
            <div class="slidetabs">
                <%= link_to "#"%>
                <%= link_to "#"%>
                <%= link_to "#"%>
            </div>

            <br/><br/>

            <div class="play">PLAY</div>
            <div class="stop">STOP</div>

            <!-- Slideshow here! -->

<% end %>

<% content_for :right do %>

    <h1>Főmenü</h1>
    <% @contents.each do |content| %>
      <div class="menu_title"><%= link_to"#{content.title}", content_home_path(content) %></div>
    <% end %>

    <br/>

    <!-- SCROLLABLE -->

    <h1>Hírek, aktualitások</h1>

    <div id="actions">
      <div class="span-2">
        <a class="prev">Előző</a>
      </div>
      <div class="span-2 last append-3">
        <a class="next">Következő</a>
      </div>
    </div>

    <br/><br/>

    <!-- root element for scrollable -->
    <div class="scrollable vertical" id="scroller">

      <!-- root element for the scrollable elements -->
      <div class="items"> <!-- START ITEMS -->

      <% div_value = 1 %>

            <% @advices.each do |advice| %>
              <% value = div_value.modulo(3) %>
              <% if value == 1 %>
                <div class="third"> <!-- third start -->
                  <% truncated_title = truncate("#{advice.title}", :length => 26, :omission => "...") %>
                  <div class="advice_title"><%= link_to "#{truncated_title}", advice_home_path(advice) %></div>
                    <div class="advice_content">
                      <% truncated_advice = truncate("#{advice.description}", :length => 200, :omission => "...") %>
                      <%= raw truncated_advice %>
                      <%= link_to image_tag("read_more.jpg"), advice_home_path(advice), :class => "read_more" %>
                    </div>

              <% elsif value == 2  %>
                  <% truncated_title = truncate("#{advice.title}", :length => 26, :omission => "...") %>
                  <div class="advice_title"><%= link_to "#{truncated_title}", advice_home_path(advice) %></div>
                  <div class="advice_content">
                  <% truncated_advice = truncate("#{advice.description}", :length => 200, :omission => "...") %>
                  <%= raw truncated_advice %>
                  <%= link_to image_tag("read_more.jpg"), advice_home_path(advice), :class => "read_more" %>
                  </div>

              <% else %>
                  <% truncated_title = truncate("#{advice.title}", :length => 26, :omission => "...") %>
                  <div class="advice_title"><%= link_to "#{truncated_title}", advice_home_path(advice) %></div>
                  <div class="advice_content">
                  <% truncated_advice = truncate("#{advice.description}", :length => 200, :omission => "...") %>
                  <%= raw truncated_advice %>
                  <%= link_to image_tag("read_more.jpg"), advice_home_path(advice), :class => "read_more" %>
                  </div>
               </div> <!-- third end -->
              <% end %>

              <% div_value += 1 %>

            <% end %>

      </div> <!-- END ITEMS -->
    </div>

    <!-- SCROLLABLE -->

<% end %>

<% if @tabs.empty? %>
    <% content_for :tab do %>
        <!-- NINCS HOZZARENDELT TAB -->
    <% end %>
<% else %>
    <% content_for :tab do %>
        <h1><%= @info_name %></h1>
        <ul class="tabs">
          <% @tabs.each do |tab| %>
              <li><%= link_to "#{tab.title}", "#", :class => "m" %></li>
          <% end %>
        </ul>

        <!-- tab "panes" -->
        <div class="panes">
          <% @tabs.each do |tab| %>
              <div><%= raw tab.description %></div>
          <% end %>
        </div>

    <% end %>

<% end %>

app/views/shared/_stylesheet.html.erb
<% @stylesheets.each do |stylesheet| %>
  <% case stylesheet.name_value %>
  <% when "mikrovoks" %>
    <%= stylesheet_link_tag "mikrovoks/mikrovoks" %>

  <% when "mvmonitor" %>
    <%= "Mikrokam" %>

  <% when "digirat" %>
    <%= "Mikrokam" %>

  <% when "mikrokam" %>
    <%= "Mikrokam" %>

  <% when "edtr" %>
    <%= "Mikrokam" %>

  <% when "sequence" %>
    <%= "Mikrokam" %>

  <% when "onkormanyzatitv" %>
    <%= "Mikrokam" %>

  <% else %>
    <%= stylesheet_link_tag "default/default" %>

  <% end %>

<% end %>