config/routes.rb
Mikrokamnew::Application.routes.draw do  

  resources :infos

  devise_for :admins

  resources :admins
  resources :tabs
  resources :advices
  resources :sliders
  resources :menus
  resources :contents
  resources :tests
  resources :stylesheets

  scope "/admin" do
    resources :menus, :contents, :sliders, :tabs
  end  

  resources :home do
    member do
      get 'content'
      get 'advice'
      get 'slider'
      get 'active_tab_ajax'
      get 'all_active'
      get 'service'
    end
  end 

  get "home/index"
  
  match 'admin' => 'admins#index'
  match 'admins' => 'admins#index'

  match "infos/:id/show_tabs" => "infos#show_tabs", :as => "show_the_tabs"
  

  root :to => "home#index"

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  #Devise
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
end

app/models/advice.rb
class Advice < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  has_one :menu
  has_one :info
  has_many :tabs, :through => :info

  # Ha azt szeretnenk hogy az url-ben szerpepljen a a tartlomnal megadott url erteke akkor ezt kell engedelyezni

  #def to_param
  #  url
  #end



end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :content
  has_many :tabs
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :content
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/styles.rb
class Styles < ActiveRecord::Base
end

app/models/stylesheet.rb
class Stylesheet < ActiveRecord::Base
end

app/models/tab.rb
class Tab < ActiveRecord::Base
  belongs_to :info
  has_one :content, :through => :info
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.xml

  layout "admin"

  def index
    @content = Content.new
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.xml
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @info }
    end
  end

  def show_tabs
   @tab = Tab.new
   @tabs = Tab.where(:info_id => (params[:id]))
  end

  # GET /infos/new
  # GET /infos/new.xml
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.xml
  def create
    @info = Info.new(params[:info])
      if @info.save
        redirect_to infos_path, :notice => 'Info was successfully created.'
      else
        render :action => "new"
      end
  end

  # PUT /infos/1
  # PUT /infos/1.xml
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to(@info, :notice => 'Info was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.xml
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to(infos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/stylesheet_helper.rb
module StylesheetHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content_id %><br />
    <%= f.select("content_id", Content.all.collect {|content| [ content.title, content.id ] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Fülekkel ellátott területek</h1>

<div class="add_new">
  <%= link_to 'Új fülekkel ellátott terület létrehozása', new_info_path %>
  <%= link_to 'Vissza', admins_path %>
</div>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Cím</th>
      <th scope="col">&nbsp;</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.name %></td>
        <td><%= link_to 'Módosít', edit_info_path(info) %></td>
        <td class="delete"><%= link_to 'Töröl', info, :confirm => 'Biztosan törlöd?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @info.name %>
</p>

<p>
  <b>Content:</b>
  <%= @info.content_id %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/infos/show_tabs.erb
<h1>Tabok ehhez az infóhoz :</h1>

<table id="box-table-a">
  <thead>
    <tr>
      <th scope="col">Tab neve :</th>
    </tr>
  </thead>

  <tbody>
    <% @tabs.each do |tab| %>
      <tr>
        <td><%= tab.title %></td>
      </tr>
    <% end %>
  </tbody>

</table>